module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  transformIgnorePatterns: [
    'node_modules/(?!(uuid)/)',
  ],
  moduleNameMapper: {
    '^@ws/(.*)$': '<rootDir>/project/ws/$1',
    '@ws-widget/(.*)$': '<rootDir>/library/ws-widget/$1',
    '@ws/author/(.*)$': '<rootDir>/project/ws/author/$1',
    // '^@components/(.*)$': '<rootDir>/project/ws/author/src/lib/routing/modules/editor/routing/modules/collection-v2/components/$1',
    'worker-loader!.*': '<rootDir>/test/mocks/workerMock.js',
    'pdfjs-dist/build/pdf.worker': '<rootDir>/test/mocks/workerMock.js',
    "^src/environments/environment$": "<rootDir>/src/environments/environment.ts",
  },
  coverageDirectory: './coverage',
  coverageReporters: ["clover", "json", "lcov", "text", "text-summary"],
  collectCoverage: true,
  testResultsProcessor: "jest-sonar-reporter",
  setupFiles: ['zone.js'],
  collectCoverageFrom: [
    "src/**/*.ts",
    "src/**/*.module.ts",
    "!src/**/*.spec.ts",
    "!src/environments/*.ts",
    "library/**/*.ts",
    "library/**/*.module.ts",
    "!library/**/*.spec.ts",
    "project/**/*.ts",
    "project/**/*.module.ts",
    "!project/**/*.spec.ts",
  ],
}
